using UnityEngine;

public enum UIScreenType
{
    Login,
    Register,
    Home,
    OTP,
    BasicDetails,
    UserDetails,
    CreativeStyles,
    ModernStyles,
    Budget,
    Family,
    Location,
    OnboardingComplete,
    ColorTone,
    CreatorBasicDetails,
    CreatorLocation,
    CeatorExperience,
    forgotPassword,
    CreatorType,
    taglineSocials,
    PasswordOTP,
    PasswordReset,
    PasswordChanged,
    LoggedInProfileScreen,
    UserProfileScreen,
    CreatorProfileScreen,
    LoggedInFollowing,
    CreatorFollowing,
    UserFollowing,
}
